
haversine_gen: 
	g++ haversine_gen.cpp -o haversine_gen.out

base_parser: 
	g++ parser_main.cpp -o parser_main.out

clean:
	rm -f haversine_gen.out parser_main.out


.PHONY: haversine_gen base_parser
